import { PrismaClient } from "../src/generated/prisma/client"
import { PrismaLibSql } from "@prisma/adapter-libsql"

import { resolve } from "path"
const dbPath = resolve(__dirname, "..", "dev.db")
const adapter = new PrismaLibSql({ url: `file:${dbPath}` })
const prisma = new PrismaClient({ adapter })

async function main() {
  console.log("Seeding database...")

  // ─── Clear all existing records ──────────────────────────────────
  await prisma.newsItem.deleteMany()
  await prisma.patent.deleteMany()
  await prisma.softwareResource.deleteMany()
  await prisma.honor.deleteMany()
  await prisma.talk.deleteMany()
  await prisma.grant.deleteMany()
  await prisma.publication.deleteMany()
  await prisma.appointment.deleteMany()
  await prisma.personProfile.deleteMany()
  await prisma.photoAsset.deleteMany()
  await prisma.inquirySubmission.deleteMany()
  await prisma.user.deleteMany()

  console.log("Cleared all existing records.")

  // ─── Person Profile ──────────────────────────────────────────────
  await prisma.personProfile.create({
    data: {
      name: "Jake Y. Chen",
      title: "Triton Endowed Professor of Biomedical Informatics and Data Science",
      bio: "Dr. Jake Y. Chen is the Triton Endowed Professor of Biomedical Informatics and Data Science at the UAB School of Medicine, with joint appointments in Genetics, Computer Science, and Biomedical Engineering, and is the founding director of the Systems Pharmacology AI Research Center (SPARC). Over 25 years, he has advanced AI-driven biomedical informatics, network/systems biology, and computational drug discovery — developing systems pharmacology models, multi-omics AI frameworks, and digital twin simulations that integrate clinical, genomic, and real-world data for precision medicine. He has 200+ peer-reviewed publications and 200+ invited talks worldwide.\n\nDr. Chen also leads and convenes large, multi-institutional collaborations and contributes to national biomedical AI strategy and translational informatics infrastructure. He serves as the Contact MPI for CONNECT, an NIH U54-funded national AI-infrastructure initiative (2024-2029) focused on building AI-ready biomedical knowledge networks and has advised NIH and the U.S. Congress (via NIDDK panels) while collaborating with FDA efforts related to AI-driven biomedical innovation. A recognized leader in AI-driven systems pharmacology, he is a Fellow of ACMI, AIMBE, and AMIA, an ACM Distinguished Member, and has received honors including the 'Top 100 AI Leaders in Drug Discovery and Healthcare' (Deep Knowledge Analytics, 2019).",
      shortBio: "25+ years advancing AI-driven biomedical informatics, network/systems biology, and computational drug discovery. 200+ publications, 200+ invited talks, >$100M in grants.",
      email: "jakechen@uab.edu",
      featuredMetrics: JSON.stringify({
        publications: "200+",
        talks: "200+",
        grants: ">$100M",
        years: "25+",
      }),
    },
  })

  // ─── Appointments (Education & Career) ───────────────────────────
  const appointments = [
    { institution: "Peking University", role: "B.S. in Biochemistry & Molecular Biology", department: "Department of Biochemistry & Molecular Biology, College of Life Sciences", startYear: 1995, endYear: 1995, type: "EDUCATION", location: "Peking University", sortOrder: 1 },
    { institution: "University of Minnesota", role: "M.S. in Computer Science & Engineering", department: "Department of Computer Science & Engineering", startYear: 1997, endYear: 1997, type: "EDUCATION", location: "Minneapolis, MN", sortOrder: 3 },
    { institution: "University of Minnesota", role: "Ph.D. in Computer Science & Engineering", department: "Department of Computer Science & Engineering", startYear: 2001, endYear: 2001, type: "EDUCATION", location: "Minneapolis, MN", sortOrder: 4 },
    { institution: "Affymetrix Inc.", role: "Bioinformatics Computer Scientist", department: null, startYear: 1998, endYear: 2002, type: "INDUSTRY", location: "Santa Clara, CA", sortOrder: 5 },
    { institution: "Myriad Proteomics", role: "Head of Computational Proteomics", department: null, startYear: 2002, endYear: 2003, type: "INDUSTRY", location: "Salt Lake City, UT", sortOrder: 6 },
    { institution: "Purdue University", role: "Visiting Assistant Professor of Computer Science", department: "Department of Computer Science", startYear: 2004, endYear: 2004, type: "FACULTY", location: "Indianapolis, IN", sortOrder: 7 },
    { institution: "Indiana University School of Informatics / Purdue", role: "Assistant Professor", department: null, startYear: 2004, endYear: 2010, type: "FACULTY", location: "Indianapolis, IN", sortOrder: 8 },
    { institution: "Indiana University School of Informatics / Purdue", role: "Associate Professor (tenured)", department: null, startYear: 2010, endYear: 2016, type: "FACULTY", location: "Indianapolis, IN", sortOrder: 9 },
    { institution: "IU-Purdue", role: "Founding Director, Indiana Center for Systems Biology and Personalized Medicine", department: null, startYear: 2007, endYear: 2016, type: "FACULTY", location: "Indianapolis, IN", sortOrder: 10 },
    { institution: "UAB", role: "Professor (with tenure), Dept of Genetics", department: "Department of Genetics", startYear: 2016, endYear: 2023, type: "FACULTY", location: "Birmingham, AL", sortOrder: 11 },
    { institution: "UAB", role: "Associate Director & Chief Bioinformatics Officer, Informatics Institute", department: "Informatics Institute", startYear: 2016, endYear: 2023, type: "FACULTY", location: "Birmingham, AL", sortOrder: 12 },
    { institution: "UAB", role: "Professor (secondary), Computer and Information Sciences", department: "Department of Computer and Information Sciences", startYear: 2017, endYear: null, type: "FACULTY", location: "Birmingham, AL", sortOrder: 13 },
    { institution: "UAB", role: "Professor (secondary), Biomedical Engineering", department: "Department of Biomedical Engineering", startYear: 2018, endYear: null, type: "FACULTY", location: "Birmingham, AL", sortOrder: 14 },
    { institution: "UAB", role: "Triton Endowed Professor, Biomedical Informatics and Data Science", department: "Department of Biomedical Informatics and Data Science", startYear: 2023, endYear: null, type: "FACULTY", location: "Birmingham, AL", sortOrder: 15 },
    { institution: "UAB", role: "Founding Director, SPARC", department: "Systems Pharmacology AI Research Center", startYear: 2023, endYear: null, type: "FACULTY", location: "Birmingham, AL", sortOrder: 16 },
  ]
  for (const appt of appointments) {
    await prisma.appointment.create({ data: appt })
  }

  // ─── Publications ────────────────────────────────────────────────
  const publications = [
    // ── 2025 ──
    {
      title: "Shaping the Glioblastoma Microenvironment to Enhance CAR-NK Immunotherapy",
      authors: "Emily Tang and Jake Y. Chen*",
      year: 2025,
      journal: "Frontiers in Immunology",
      doi: "10.3389/fimmu.2025.1681966",
      tags: JSON.stringify(["Immunology", "Drug Discovery"]),
      researchLineage: "Systems Pharmacology",
      articleType: "Journal Article",
    },
    {
      title: "GETgene-AI: a framework for prioritizing actionable cancer drug targets",
      authors: "Adrian Gu and Jake Y. Chen*",
      year: 2025,
      journal: "Frontiers in Systems Biology",
      doi: "10.3389/fsysb.2025.1649758",
      tags: JSON.stringify(["AI/ML", "Drug Discovery"]),
      researchLineage: "Systems Pharmacology",
      articleType: "Journal Article",
    },
    {
      title: "Targeting west nile virus replication by xanthine inhibitors",
      authors: "Theresa H. Nguyen, Jessica L. Smith, Shuklendu D. Karyakarte, John P. Tillotson, Sarah C. Sarngadharan, Fuad Al Abir, Jake Y. Chen, Sixue Zhang, Lynn Rasmussen, Robert Bostwick, Alec J. Hirsch, Corinne E. Augelli-Szafran, Ashish K. Pathak, Omar Mouhka-Chafiq",
      year: 2025,
      journal: "Medicinal Chemistry Research",
      doi: "10.1007/s00044-025-03481-7",
      tags: JSON.stringify(["Drug Discovery", "Virology"]),
      researchLineage: "Systems Pharmacology",
      articleType: "Journal Article",
    },
    {
      title: "LlamaAffinity: A Predictive Antibody Antigen Binding Model Integrating Antibody Sequences with Llama3 Backbone Architecture",
      authors: "Delower Hossain, Ehsan Saghapour, Kevin Song, and Jake Y. Chen*",
      year: 2025,
      journal: "bioRxiv",
      doi: "10.1101/2025.05.28.653051",
      tags: JSON.stringify(["AI/ML", "Drug Discovery"]),
      researchLineage: "Systems Pharmacology",
      articleType: "Preprint",
    },
    {
      title: "LLM Agent Swarm for Hypothesis-Driven Drug Discovery",
      authors: "Kevin Song, Andrew Trotter, Jake Y. Chen*",
      year: 2025,
      journal: "arXiv",
      arxivId: "2504.17967",
      tags: JSON.stringify(["AI/ML", "Drug Discovery"]),
      researchLineage: "Systems Pharmacology",
      articleType: "Preprint",
    },
    {
      title: "Integrative multi-scale network simulation for precision drug repurposing with PETS",
      authors: "Kevin Song and Jake Y. Chen*",
      year: 2025,
      journal: "bioRxiv",
      doi: "10.1101/2025.02.24.639994",
      tags: JSON.stringify(["Systems Biology", "Drug Discovery"]),
      researchLineage: "Systems Pharmacology",
      articleType: "Preprint",
    },
    {
      title: "GOALS: Gene Ontology Analysis with Layered Shells for Enhanced Functional Insight and Visualization",
      authors: "Zongliang Yue, Robert S. Welner, Christopher D. Willey, Rajesh Amin, and Jake Y. Chen*",
      year: 2025,
      journal: "bioRxiv",
      doi: "10.1101/2025.04.22.650095",
      tags: JSON.stringify(["Bioinformatics", "Multi-omics"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Preprint",
    },
    {
      title: "KinoViz: A User-Friendly Web Application for High-Throughput Kinome Profiling Analysis and Visualization in Cancer Research",
      authors: "Ehsan Saghapour, JC Anderson, Jake Y. Chen, Christopher D. Willey",
      year: 2025,
      journal: "Res Sq",
      doi: "10.21203/rs.3.rs-6431257/v1",
      tags: JSON.stringify(["Visualization", "Cancer"]),
      researchLineage: "Multi-omics & Interpretable AI",
      articleType: "Preprint",
    },
    {
      title: "Toden-E: Topology-Based and Density-Based Ensembled Clustering for the Development of Super-PAG in Functional Genomics using PAG Network and LLM",
      authors: "Li Q, Nichols C, Welner RS, Jake Y. Chen, Ku WS, Yue Z",
      year: 2025,
      journal: "bioRxiv",
      doi: "10.1101/2024.10.20.619308",
      tags: JSON.stringify(["AI/ML", "Bioinformatics"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Preprint",
    },
    {
      title: "AI-Driven Network Biology Identifies SRC as a Therapeutic Target in Metastatic Pancreatic Adenocarcinoma",
      authors: "Ayla Zhang and Jake Y. Chen*",
      year: 2025,
      journal: "Intelligent Oncology",
      doi: "10.1016/j.intonc.2025.06.004",
      tags: JSON.stringify(["AI/ML", "Drug Discovery", "Knowledge Networks"]),
      researchLineage: "Systems Pharmacology",
      articleType: "Journal Article",
    },
    {
      title: "High-throughput screening for the identification of dual inhibitors of BRD4 and RIPK3",
      authors: "Yatchang MF, Zhai L, Moukha-Chafiq O, et al., Jake Y. Chen, et al.",
      year: 2025,
      journal: "SLAS Discovery",
      doi: "10.1016/j.slasd.2025.100247",
      tags: JSON.stringify(["Drug Discovery", "High-throughput Screening"]),
      researchLineage: "Systems Pharmacology",
      articleType: "Journal Article",
    },
    {
      title: "Temporal GeneTerrain: Advancing Precision Medicine Through Dynamic Gene Expression Visualization",
      authors: "Ehsan Saghapour, Rahul Sharma, Delower Hossain, Kevin Song, Zhandos Sembay, and Jake Y Chen*",
      year: 2025,
      journal: "Frontiers in Bioinformatics",
      doi: "10.3389/fbinf.2025.1602850",
      tags: JSON.stringify(["Visualization", "Precision Medicine"]),
      researchLineage: "Multi-omics & Interpretable AI",
      articleType: "Journal Article",
    },
    {
      title: "NeSyDPP4-QSAR: Discovering DPP-4 Inhibitors for Diabetes Treatment with a Neuro-symbolic AI Approach",
      authors: "Delower Hossain, Ehsan Saghapour, and Jake Y. Chen*",
      year: 2025,
      journal: "Frontiers in Bioinformatics",
      doi: "10.3389/fbinf.2025.1603133",
      tags: JSON.stringify(["AI/ML", "Drug Discovery"]),
      researchLineage: "Systems Pharmacology",
      articleType: "Journal Article",
    },
    {
      title: "A Study on Neuro-Symbolic Artificial Intelligence: Healthcare Perspectives",
      authors: "Delower Hossain and Jake Y. Chen*",
      year: 2025,
      journal: "arXiv",
      arxivId: "2503.18213",
      tags: JSON.stringify(["AI/ML", "Healthcare"]),
      researchLineage: "Multi-omics & Interpretable AI",
      articleType: "Preprint",
    },
    {
      title: "A Hybrid Chaos-Based Cryptographic Framework for Post-Quantum Secure Communications",
      authors: "Kevin Song, Noorullah Imran, Jake Y. Chen, Allan C. Dobbins",
      year: 2025,
      journal: "arXiv",
      arxivId: "2504.08618",
      tags: JSON.stringify(["AI/ML", "Security"]),
      researchLineage: "Multi-omics & Interpretable AI",
      articleType: "Preprint",
    },
    // ── 2024 ──
    {
      title: "MLPA: A Multi-scale Digital Twin Framework for Personalized Cancer Simulation and Treatment Optimization",
      authors: "James Gu and Jake Y. Chen*",
      year: 2024,
      journal: "bioRxiv",
      doi: "10.1101/2024.09.13.612988",
      tags: JSON.stringify(["Digital Twins", "Precision Medicine"]),
      researchLineage: "Digital Twins & Precision Medicine",
      articleType: "Preprint",
    },
    {
      title: "Mondrian Abstraction and Language Model Embeddings for Differential Pathway Analysis",
      authors: "Fuad Al Abir and Jake Y. Chen*",
      year: 2024,
      journal: "bioRxiv",
      doi: "10.1101/2024.04.11.589093",
      tags: JSON.stringify(["AI/ML", "Bioinformatics"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Preprint",
    },
    {
      title: "AI-readiness for Biomedical Data: Bridge2AI Recommendations",
      authors: "Clark T, Caufield H, ... Jake Y. Chen, ... Munoz-Torres MC",
      year: 2024,
      journal: "bioRxiv",
      doi: "10.1101/2024.10.23.619844",
      tags: JSON.stringify(["AI/ML", "Translational"]),
      researchLineage: "Translational Data Infrastructure",
      articleType: "Preprint",
    },
    {
      title: "Cell Maps for Artificial Intelligence: AI-Ready Maps of Human Cell Architecture from Disease-Relevant Cell Lines",
      authors: "Clark T, Mohan J, ... Jake Chen, ... Ideker T",
      year: 2024,
      journal: "bioRxiv",
      doi: "10.1101/2024.05.21.589311",
      tags: JSON.stringify(["AI/ML", "Systems Biology"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Preprint",
    },
    {
      title: "Pharmacogenomics of Coronary Artery Response to Intravenous Gamma Globulin in Kawasaki Disease",
      authors: "Sadeep Shrestha, Howard Wiener, et al., Jake Chen, et al.",
      year: 2024,
      journal: "npj Genomic Medicine",
      doi: "10.1038/s41525-024-00419-7",
      tags: JSON.stringify(["Precision Medicine", "Multi-omics"]),
      researchLineage: "Translational Data Infrastructure",
      articleType: "Journal Article",
    },
    {
      title: "An NLP-based Technique to Extract Meaningful Features from Drug SMILES",
      authors: "Rahul Sharma, Ehsan Saghapour, and Jake Y. Chen*",
      year: 2024,
      journal: "iScience",
      doi: "10.1016/j.isci.2024.109127",
      tags: JSON.stringify(["AI/ML", "Drug Discovery"]),
      researchLineage: "Systems Pharmacology",
      articleType: "Journal Article",
    },
    {
      title: "PAGER-scFGA: Unveiling Cell Functions and Molecular Mechanisms in Cell Trajectories through Single-Cell Functional Genomics Analysis",
      authors: "Fengyuan Huang, Robert Welner, Jake Y Chen*, and Zongliang Yue*",
      year: 2024,
      journal: "Frontiers in Bioinformatics",
      doi: "10.3389/fbinf.2024.1336135",
      tags: JSON.stringify(["Multi-omics", "Bioinformatics"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Journal Article",
    },
    {
      title: "Pharmacogenomics of intravenous immunoglobulin response in Kawasaki disease",
      authors: "Sadeep Shrestha, et al., Jake Y. Chen, et al.",
      year: 2024,
      journal: "Frontiers in Immunology",
      doi: "10.3389/fimmu.2023.1287094",
      tags: JSON.stringify(["Precision Medicine", "Immunology"]),
      researchLineage: "Translational Data Infrastructure",
      articleType: "Journal Article",
    },
    {
      title: "Photo-neuro-immuno-endocrinology: how the Ultraviolet Radiation Regulates the Body, Mind, and Immune System",
      authors: "Radomir M. Slominski, Jake Y. Chen, Chander Raman, Andrzej Slominski",
      year: 2024,
      journal: "PNAS",
      doi: "10.1073/pnas.2308374121",
      tags: JSON.stringify(["Systems Biology", "Translational"]),
      researchLineage: "Translational Data Infrastructure",
      articleType: "Journal Article",
      featured: true,
    },
    // ── 2023 ──
    {
      title: "Prioritizing Complex Disease Genes from Heterogeneous Public Databases",
      authors: "Eric Gong and Jake Y. Chen*",
      year: 2023,
      journal: "Biomedical Sciences Instrumentation",
      doi: null,
      tags: JSON.stringify(["Bioinformatics", "Knowledge Networks"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Journal Article",
    },
    {
      title: "Analysis of Cardiac Single-cell RNA-sequencing Data Can be Improved by the Use of Artificial-Intelligence-based Tools",
      authors: "Thanh Nguyen, Yuhua Wei, et al.",
      year: 2023,
      journal: "Scientific Reports",
      doi: "10.1038/s41598-023-32293-1",
      tags: JSON.stringify(["Multi-omics", "AI/ML"]),
      researchLineage: "Multi-omics & Interpretable AI",
      articleType: "Journal Article",
    },
    {
      title: "Biological Network Mining",
      authors: "Zongliang Yue*, Da Yan*, Guimu Guo, and Jake Y. Chen",
      year: 2023,
      journal: "Biostatistics Research",
      doi: null,
      tags: JSON.stringify(["Knowledge Networks", "Systems Biology"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Journal Article",
    },
    {
      title: "How Cancer Hijacks the Body's Homeostasis through the Neuroendocrine System and Why",
      authors: "Radomir M. Slominski, Chander Raman, Jake Y. Chen, and Andrzej T. Slominski*",
      year: 2023,
      journal: "Trends in Neurosciences",
      doi: "10.1016/j.tins.2023.01.003",
      tags: JSON.stringify(["Systems Biology", "Translational"]),
      researchLineage: "Translational Data Infrastructure",
      articleType: "Journal Article",
    },
    // ── 2022 ──
    {
      title: "Neuroendocrine Signaling in the Skin",
      authors: "Andrzej T. Slominski, et al., Jake Y. Chen, et al.",
      year: 2022,
      journal: "American Journal of Physiology-Cell Physiology",
      doi: null,
      tags: JSON.stringify(["Systems Biology", "Translational"]),
      researchLineage: "Translational Data Infrastructure",
      articleType: "Journal Article",
    },
    {
      title: "WINNER: A network biology tool for biomolecular characterization and prioritization",
      authors: "Thanh Nguyen, Zongliang Yue, et al., Jake Y. Chen*",
      year: 2022,
      journal: "Frontiers in Big Data",
      doi: "10.3389/fdata.2022.1016606",
      tags: JSON.stringify(["Knowledge Networks", "Systems Biology"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Journal Article",
    },
    {
      title: "A Crowdsourcing Approach to Develop Machine Learning Models to Quantify Radiographic Joint Damage in Rheumatoid Arthritis",
      authors: "Dongmei Sun, Thanh M. Nguyen, et al., Jake Y. Chen*, James C. Costello*, and S. Louis Bridges, Jr.*",
      year: 2022,
      journal: "JAMA Network Open",
      doi: "10.1001/jamanetworkopen.2022.27423",
      tags: JSON.stringify(["AI/ML", "Translational"]),
      researchLineage: "Multi-omics & Interpretable AI",
      articleType: "Journal Article",
      featured: true,
    },
    {
      title: "A Novel in vivo Model of Glioblastoma Radiation Resistance Identifies Long Non-coding RNAs and Targetable Kinases",
      authors: "Christian T. Stackhouse, et al., Jake Y. Chen, et al.",
      year: 2022,
      journal: "JCI Insights",
      doi: "10.1172/jci.insight.148717",
      tags: JSON.stringify(["Drug Discovery", "Translational"]),
      researchLineage: "Systems Pharmacology",
      articleType: "Journal Article",
    },
    {
      title: "DEMA: a Distance-bounded Energy-field Minimization Algorithm to Model and Layout Bio-molecular Networks with Quantitative Features",
      authors: "Zhenyu Weng, Zongliang Yue, Yuesheng Zhu, and Jake Y. Chen*",
      year: 2022,
      journal: "Bioinformatics",
      doi: "10.1093/bioinformatics/btac261",
      tags: JSON.stringify(["Bioinformatics", "Visualization"]),
      researchLineage: "Multi-omics & Interpretable AI",
      articleType: "Journal Article",
    },
    {
      title: "Single Nucleus Transcriptomics: Apical Resection in Newborn Pigs",
      authors: "Jianyi Zhang* et al., Jake Y. Chen, et al.",
      year: 2022,
      journal: "Circulation",
      doi: null,
      tags: JSON.stringify(["Multi-omics", "Translational"]),
      researchLineage: "Translational Data Infrastructure",
      articleType: "Journal Article",
    },
    {
      title: "PAGER Web APP: An Interactive, Online Gene Set and Network Interpretation Tool",
      authors: "Zongliang Yue, Radomir Slominski, Samuel Bharti, and Jake Y Chen*",
      year: 2022,
      journal: "Frontiers in Genetics",
      doi: "10.3389/fgene.2022.820361",
      tags: JSON.stringify(["Knowledge Networks", "Bioinformatics"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Journal Article",
    },
    {
      title: "Polar Gini Curve",
      authors: "Thanh Nguyen, Jacob Jeevan, Nuo Xu, and Jake Y. Chen*",
      year: 2022,
      journal: "Genomics, Proteomics, and Bioinformatics",
      doi: "10.1016/j.gpb.2020.09.006",
      tags: JSON.stringify(["Multi-omics", "Bioinformatics"]),
      researchLineage: "Multi-omics & Interpretable AI",
      articleType: "Journal Article",
    },
    {
      title: "A Non-redundant Role for T cell-derived IL-22 in Antibacterial Defense of Colonic Crypts",
      authors: "Carlene L. Zindl, et al., Jake Y. Chen, et al.",
      year: 2022,
      journal: "Immunity",
      doi: null,
      tags: JSON.stringify(["Immunology", "Systems Biology"]),
      researchLineage: "Translational Data Infrastructure",
      articleType: "Journal Article",
      featured: true,
    },
    // ── 2021 ──
    {
      title: "Statistical Enrichment Analysis of Samples (SEAS)",
      authors: "Thanh Minh Nguyen, et al. and Jake Y Chen*",
      year: 2021,
      journal: "Frontiers in Big Data",
      doi: "10.3389/fdata.2021.725276",
      tags: JSON.stringify(["Bioinformatics", "Multi-omics"]),
      researchLineage: "Multi-omics & Interpretable AI",
      articleType: "Journal Article",
    },
    {
      title: "Guest Editorial for Selected Papers From BIOKDD 2019",
      authors: "D. Yan*, S. Thankachan and Jake Y. Chen*",
      year: 2021,
      journal: "IEEE/ACM Transactions on Computational Biology and Bioinformatics",
      doi: "10.1109/TCBB.2021.3067071",
      tags: JSON.stringify(["Bioinformatics"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Journal Article",
    },
    {
      title: "Metabolic alterations mediated by STAT3 promotes drug persistence in CML",
      authors: "Sweta B. Patel, et al., Jake Y. Chen, et al.",
      year: 2021,
      journal: "Leukemia",
      doi: null,
      tags: JSON.stringify(["Drug Discovery", "Translational"]),
      researchLineage: "Systems Pharmacology",
      articleType: "Journal Article",
    },
    {
      title: "Vitamin D and Lumisterol Derivatives Can Act on Liver X Receptors (LXRs)",
      authors: "Andrzej T Slominski, et al., Jake Y. Chen, et al.",
      year: 2021,
      journal: "Scientific Reports",
      doi: null,
      tags: JSON.stringify(["Systems Biology", "Drug Discovery"]),
      researchLineage: "Translational Data Infrastructure",
      articleType: "Journal Article",
    },
    {
      title: "Linking Clinotypes to Phenotypes and Genotypes",
      authors: "Thanh Nguyen, Tongbin Zhang, et al., and Jake Y. Chen*",
      year: 2021,
      journal: "BMC Medical Informatics and Decision Making",
      doi: "10.1186/s12911-021-01387-z",
      tags: JSON.stringify(["Precision Medicine", "Multi-omics"]),
      researchLineage: "Translational Data Infrastructure",
      articleType: "Journal Article",
    },
    {
      title: "PAGER-CoV: A Comprehensive Collection of Pathways, Annotated-gene-lists, and Gene Signatures for Coronavirus Disease Studies",
      authors: "Zongliang Yue, Eric Zhang, et al. and Jake Y. Chen*",
      year: 2021,
      journal: "Nucleic Acids Research",
      doi: "10.1093/nar/gkaa1094",
      tags: JSON.stringify(["Knowledge Networks", "Database"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Journal Article",
      featured: true,
    },
    {
      title: "Scalable De Novo Genome Assembly Using a Pregel-Like Graph-Parallel System",
      authors: "Guimu Guo, et al. and Jake Y. Chen",
      year: 2021,
      journal: "ACM/IEEE Transactions on Computational Biology and Bioinformatics",
      doi: "10.1109/TCBB.2019.2920912",
      tags: JSON.stringify(["Bioinformatics", "Systems Biology"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Journal Article",
    },
    // ── Selected landmark papers (pre-2021) ──
    {
      title: "Regenerative Potential of Neonatal Porcine Hearts",
      authors: "Wuqiang Zhu et al.",
      year: 2018,
      journal: "Circulation",
      doi: null,
      tags: JSON.stringify(["Systems Biology", "Translational"]),
      researchLineage: "Translational Data Infrastructure",
      articleType: "Journal Article",
      featured: true,
    },
    {
      title: "PAGER 2.0",
      authors: "Zongliang Yue et al. and Jake Y. Chen*",
      year: 2018,
      journal: "Nucleic Acids Research",
      doi: null,
      tags: JSON.stringify(["Knowledge Networks", "Database"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Journal Article",
      featured: true,
    },
    {
      title: "Building Disease-specific Drug-Protein Connectivity Maps",
      authors: "Jiao Li, Xiaoyan Zhu, and Jake Y. Chen*",
      year: 2009,
      journal: "PLoS Computational Biology",
      doi: null,
      tags: JSON.stringify(["Drug Discovery", "Knowledge Networks"]),
      researchLineage: "Systems Pharmacology",
      articleType: "Journal Article",
      featured: true,
    },
    {
      title: "DisProt: The Database of Disordered Proteins",
      authors: "Megan Sickmeier et al.",
      year: 2007,
      journal: "Nucleic Acids Research",
      doi: null,
      tags: JSON.stringify(["Database", "Bioinformatics"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Journal Article",
    },
    {
      title: "Genomic Data Modeling",
      authors: "Jake Y. Chen and John Carlis",
      year: 2003,
      journal: "Information Systems",
      doi: null,
      tags: JSON.stringify(["Bioinformatics", "Database"]),
      researchLineage: "Biomedical Knowledge Networks",
      articleType: "Journal Article",
    },
  ]
  for (const pub of publications) {
    await prisma.publication.create({ data: pub })
  }

  // ─── Honors ──────────────────────────────────────────────────────
  const honors = [
    { awardName: "Top 100 AI Leaders in Drug Discovery and Advanced Healthcare", year: 2019, issuer: "Deep Knowledge Analytics" },
    { awardName: "ACM Distinguished Member", year: 2021, issuer: "ACM" },
    { awardName: "Elected Fellow, AIMBE", year: 2021, issuer: "AIMBE" },
    { awardName: "Elected Fellow, AMIA", year: 2020, issuer: "AMIA" },
    { awardName: "Elected Fellow, ACMI", year: 2019, issuer: "ACMI" },
    { awardName: "UAB Triton Endowed Professorship", year: 2023, issuer: "UAB Board of Trustees" },
    { awardName: "NIH Bridge2AI Grand Prize Theme Song", year: 2024, issuer: "NIH" },
    { awardName: "ISCB Senior Member", year: 2019, issuer: "ISCB" },
    { awardName: "ACM Senior Member", year: 2009, issuer: "ACM" },
    { awardName: "IEEE Senior Member", year: 2004, issuer: "IEEE" },
    { awardName: "Innocentive.com Grand Challenge Award Winner", year: 2012, issuer: "Innocentive.com" },
    { awardName: "UAB School of Medicine Featured Discovery Award", year: 2021, issuer: "UAB" },
    { awardName: "IUPUI School of Informatics Research Award", year: 2011, issuer: "IUPUI" },
    { awardName: "Canary Foundation Bioinformatics Dissemination Award", year: 2007, issuer: "Canary Foundation" },
    { awardName: "Outstanding Computer Science Graduate Research Award", year: 1998, issuer: "University of Minnesota" },
  ]
  for (const honor of honors) {
    await prisma.honor.create({ data: honor })
  }

  // ─── Grants ──────────────────────────────────────────────────────
  const grants = [
    // Current grants
    {
      agency: "NIH",
      mechanism: "U54:OD036472",
      title: "CONNECT: Collaborative Network for Nurturing Ecosystems of Common Fund Team Science",
      role: "Contact MPI",
      amount: 9437405,
      startDate: new Date("2024-04-01"),
      endDate: new Date("2029-03-31"),
      status: "Active",
      piName: "Jake Y. Chen",
    },
    {
      agency: "NIH/NIA",
      mechanism: "U24:AG098157-01",
      title: "ReCARDO: Using Real-World Data to Derive Common Data Elements for Alzheimer's Disease and AD-Related Dementias Research Through Ontological Innovation",
      role: "Co-investigator and UAB Site PI",
      amount: 19977000,
      startDate: new Date("2025-09-01"),
      endDate: new Date("2030-08-31"),
      status: "Active",
      piName: "Guo-Qiang Zhang",
    },
    {
      agency: "NIH",
      mechanism: "1OT2-OD032742-01",
      title: "Building an Interpretable Genomic Translator Using Maps of Cell Architecture",
      role: "MPI",
      amount: 2100000,
      startDate: new Date("2022-09-01"),
      endDate: new Date("2026-08-31"),
      status: "Active",
      piName: "Trey Ideker",
    },
    {
      agency: "NIH/NIDDK",
      mechanism: "U54:DK137307",
      title: "UAB-UCSD O'Brien Center for Acute Kidney Injury Research",
      role: "Co-investigator",
      amount: 4572100,
      startDate: new Date("2023-07-01"),
      endDate: new Date("2028-06-30"),
      status: "Active",
      piName: "Anupam Agarwal",
    },
    {
      agency: "NAIRR",
      mechanism: "NAIRR Pilot Grants",
      title: "Computing for AI-enabled Systems Pharmacology and Drug Discovery",
      role: "PI",
      amount: 130000,
      startDate: new Date("2025-12-01"),
      endDate: new Date("2026-11-30"),
      status: "Active",
      piName: "Jake Y. Chen",
    },
    {
      agency: "NCATS/NIH",
      mechanism: "UM1TR004771",
      title: "UAB Center for Clinical and Translational Science (CCTS)",
      role: "Co-investigator",
      amount: 68363123,
      startDate: new Date("2024-05-01"),
      endDate: new Date("2031-04-30"),
      status: "Active",
      piName: "Orlando Gutierrez",
    },
    // Completed grants
    {
      agency: "NCI/NIH",
      mechanism: "U01CA223976",
      title: "Biological Comparisons among Three Derivative Models of Glioma Patient Cancers under Microenvironmental Stress",
      role: "MPI",
      amount: 3272844,
      startDate: new Date("2018-09-01"),
      endDate: new Date("2024-12-31"),
      status: "Completed",
      piName: "Christopher Willey",
    },
    {
      agency: "NCI/NIH",
      mechanism: "R01CA258248-01A1",
      title: "R01CA258248-01A1",
      role: "Co-investigator",
      amount: 2893751,
      startDate: new Date("2022-01-12"),
      endDate: new Date("2024-12-31"),
      status: "Completed",
      piName: "Ryan Miller",
    },
    {
      agency: "NCI/NIH",
      mechanism: "R01HL150078",
      title: "R01HL150078",
      role: "Co-investigator",
      amount: 1485000,
      startDate: new Date("2020-09-15"),
      endDate: new Date("2024-05-31"),
      status: "Completed",
      piName: "Robert Welner",
    },
    {
      agency: "NIDDK/NIH",
      mechanism: "R21DK129968",
      title: "R21DK129968",
      role: "Co-PI",
      amount: 250000,
      startDate: new Date("2021-09-01"),
      endDate: new Date("2024-08-30"),
      status: "Completed",
      piName: "Sushant Bhatnagar",
    },
  ]
  for (const grant of grants) {
    await prisma.grant.create({ data: grant })
  }

  // ─── Talks ───────────────────────────────────────────────────────
  const talks = [
    // Keynote talks
    {
      title: "Embracing The New Frontier: Artificial Intelligence in Research",
      venue: "2025 CCTS Translational Science Symposium",
      city: "Gulf Shores",
      country: "USA",
      date: new Date("2025-10-01"),
      talkType: "Keynote",
      topic: "AI in Research",
    },
    {
      title: "The AI Drug Discovery Initiative at UAB",
      venue: "AI in Medicine and Nursing Symposium",
      city: "Birmingham",
      country: "USA",
      date: new Date("2024-10-01"),
      talkType: "Keynote",
      topic: "Drug Discovery",
    },
    {
      title: "Igniting the SPARC of AI-Enabled Drug Discovery",
      venue: "Southeast Clinical and Translational Science Alliances (CTSA) Annual Conference",
      city: "Pine Mountain",
      country: "USA",
      date: new Date("2024-02-01"),
      talkType: "Keynote",
      topic: "Drug Discovery",
    },
    {
      title: "Artificial Intelligence and Metal Healthcare",
      venue: "2023 Alabama Behavioral Healthcare Conference",
      city: "Birmingham",
      country: "USA",
      date: new Date("2023-11-01"),
      talkType: "Keynote",
      topic: "AI in Healthcare",
    },
    {
      title: "PAGER-CoV: An Online Curated Gene Signature Database Resource for Coronavirus Disease Functional Genomic Studies",
      venue: "19th International Workshop on Data Mining in Bioinformatics (BIOKDD), 2020 Annual ACM KDD Conference",
      city: "San Diego",
      country: "USA",
      date: new Date("2020-08-01"),
      talkType: "Keynote",
      topic: "Knowledge Networks",
    },
    {
      title: "Modeling Networks to Accelerate Biomedical Discoveries in Translational Medicine",
      venue: "2nd International Translational and Regenerative Medicine Conference",
      city: "Valencia",
      country: "Spain",
      date: new Date("2019-05-01"),
      talkType: "Keynote",
      topic: "Systems Biology",
    },
    {
      title: "Network Biology Modeling in Translational Bioinformatics",
      venue: "Workshop on Knowledge Discovery and Data Mining in Bioinformatics (BIOKDD), 2018 Annual ACM KDD Conference",
      city: "London",
      country: "UK",
      date: new Date("2018-08-01"),
      talkType: "Keynote",
      topic: "Knowledge Networks",
    },
    {
      title: "Unravel Complex Patterns in Omics Data with Integrative GNPA Tools",
      venue: "6th Annual LA Conference on Computational Biology & Bioinformatics",
      city: "Baton Rouge",
      country: "USA",
      date: new Date("2018-04-01"),
      talkType: "Keynote",
      topic: "Multi-omics",
    },
    {
      title: "Modeling Drug Efficacy Using Network Pharmacology",
      venue: "Annual Cambridge Health Institute Molecular Medicine Tri-conference",
      city: "San Francisco",
      country: "USA",
      date: new Date("2012-02-01"),
      talkType: "Keynote",
      topic: "Systems Pharmacology",
    },
    {
      title: "Translational Bioinformatics: Power Tools for Predictive and Personalized Medicine",
      venue: "International Symposium on Biocomputing",
      city: "Calicut, Kerala",
      country: "India",
      date: new Date("2010-02-01"),
      talkType: "Keynote",
      topic: "Precision Medicine",
    },
    {
      title: "ProteoLens: a Visual Analytic Tool for Multi-scale Database-driven Biological Network Data Mining",
      venue: "Fifth Annual Conference of the MidSouth Computational Biology and Bioinformatics Society",
      city: "Oklahoma City",
      country: "USA",
      date: new Date("2008-02-01"),
      talkType: "Keynote",
      topic: "Visualization",
    },
    {
      title: "Translational Systems Biology: A Prelude",
      venue: "2nd IEEE International Workshop on Data Mining in Bioinformatics",
      city: "Fremont",
      country: "USA",
      date: new Date("2007-11-01"),
      talkType: "Keynote",
      topic: "Systems Biology",
    },
    // Panel talks
    {
      title: "Panel on \"the Bridge2AI Consortium\"",
      venue: "AMIA Annual Symposium",
      city: "Atlanta",
      country: "USA",
      date: new Date("2025-11-01"),
      talkType: "Panel",
      topic: "AI in Research",
    },
    {
      title: "Panel on \"Pharmacoinformatics: Integrating Data Science and Artificial Intelligence into Drug Life Cycle\"",
      venue: "AMIA Annual Symposium",
      city: "Atlanta",
      country: "USA",
      date: new Date("2025-11-01"),
      talkType: "Panel",
      topic: "Drug Discovery",
    },
    {
      title: "Panel on \"Emerging Opportunities for AI in Health, Life Sciences, and Biomedical Engineering\"",
      venue: "Alabama Higher Education AI Exchange Conference",
      city: "Tuscaloosa",
      country: "USA",
      date: new Date("2025-10-01"),
      talkType: "Panel",
      topic: "AI in Healthcare",
    },
    {
      title: "Panel on \"Using Multi-modal Patient Level Data in Discovery and Early Development\"",
      venue: "BioTechX Europe Annual Conference",
      city: "Basel",
      country: "Switzerland",
      date: new Date("2025-10-01"),
      talkType: "Panel",
      topic: "Precision Medicine",
    },
    {
      title: "Panel on \"Unlocking the Future of Healthcare through AI, Protein Engineering, and Digital Chemistry\"",
      venue: "BiotechX Europe 2024 Annual Conference",
      city: "Basel",
      country: "Switzerland",
      date: new Date("2024-10-01"),
      talkType: "Panel",
      topic: "AI in Healthcare",
    },
    {
      title: "Panel on \"AI for Drug Discovery\"",
      venue: "Workshop on AI for Drug Discovery, AIME '24",
      city: "Salt Lake City",
      country: "USA",
      date: new Date("2024-07-01"),
      talkType: "Panel",
      topic: "Drug Discovery",
    },
    {
      title: "Panel on \"Data Harmonization to Knowledge Discovery\"",
      venue: "KDD HealthDay, 30th ACM KDD Annual Conference",
      city: "Barcelona",
      country: "Spain",
      date: new Date("2024-08-01"),
      talkType: "Panel",
      topic: "Knowledge Networks",
    },
    // Selected invited presentations
    {
      title: "Cell Maps for AI",
      venue: "AMIA Annual Symposium",
      city: "Atlanta",
      country: "USA",
      date: new Date("2025-11-01"),
      talkType: "Invited",
      topic: "AI in Research",
    },
    {
      title: "Decentralizing AI-accelerated Drug Discovery",
      venue: "AMIA Annual Symposium",
      city: "Atlanta",
      country: "USA",
      date: new Date("2025-11-01"),
      talkType: "Invited",
      topic: "Drug Discovery",
    },
    {
      title: "Programmable Medicine with Digital Functional Genomics Imaging",
      venue: "Festival of Biologics Meeting",
      city: "San Diego",
      country: "USA",
      date: new Date("2025-04-01"),
      talkType: "Invited",
      topic: "Precision Medicine",
    },
    {
      title: "Programmable Medicine as a New Paradigm in Managing and Treating Chronic Diseases",
      venue: "BiotechX Europe 2024 Annual Conference",
      city: "Basel",
      country: "Switzerland",
      date: new Date("2024-10-01"),
      talkType: "Invited",
      topic: "Precision Medicine",
    },
  ]
  for (const talk of talks) {
    await prisma.talk.create({ data: talk })
  }

  // ─── Software Resources ──────────────────────────────────────────
  const software = [
    { name: "Talent Knowledge Map", description: "Collaboration with UT Austin for NIH Bridge2AI communities (2025)", url: "http://cm4aikg.vercel.app/", category: "Knowledge Graph" },
    { name: "SpatialRSP", description: "Identifying Embedding Space Patterns in Single-Cell Gene Expression Data (2024)", category: "Multi-omics" },
    { name: "Mondrian Map", description: "Piet Mondrian's Abstraction for Differential Pathway Analysis (2024)", githubUrl: "https://github.com/fuad021/mondrian-map", category: "Visualization" },
    { name: "WINNER", description: "Weighted In-Network Node Expansion and Ranking (2022)", url: "http://discovery.informatics.uab.edu/WINNER/", category: "Knowledge Graph" },
    { name: "SEAS", description: "Statistical Enrichment Analysis of Samples (2021)", url: "http://discovery.informatics.uab.edu/SEAS/", category: "Multi-omics" },
    { name: "PGC", description: "Polar Gini Curves for Finding Biomarkers from Single-cell RNA-seq (2021)", url: "http://discovery.informatics.uab.edu/PGC/", category: "Multi-omics" },
    { name: "PAGER-CoV", description: "Database of Pathways and Gene Signatures for Coronavirus Disease (2020)", url: "http://discovery.informatics.uab.edu/PAGER-COV/", category: "Database" },
    { name: "BEERE", description: "Biomedical Entity Expansion Ranking and Explorations (2019)", url: "http://discovery.informatics.uab.edu/BEERE/", category: "Knowledge Graph" },
    { name: "HAPPI", description: "Human Annotated and Predicted Protein Interactions database (2006/2017)", url: "http://discovery.informatics.uab.edu/HAPPI/", category: "Database", featured: true },
    { name: "PAGER", description: "Pathways Annotated-lists and Gene-signatures Electronic Repository (2014/2017)", url: "http://discovery.informatics.uab.edu/PAGER/", category: "Database", featured: true },
    { name: "GeneTerrain", description: "Visualization for Panel Expression Biomarker Discoveries (2008)", url: "http://discovery.informatics.uab.edu/geneterrain/", category: "Visualization", featured: true },
    { name: "HOMER", description: "Human Organ-specific Molecular Electronic Repository (2011)", url: "http://discovery.informatics.uab.edu/HOMER/", category: "Database" },
    { name: "HPD", description: "Online Integrated Human Pathway Database (2009)", url: "http://discovery.informatics.uab.edu/HPD/", category: "Database" },
    { name: "ProteoLens", description: "Visual Data Mining and Querying Tool (2006)", url: "http://bio.informatics.uab.edu/proteolens/", category: "Visualization" },
  ]
  for (const sw of software) {
    await prisma.softwareResource.create({ data: sw })
  }

  // ─── Patents ─────────────────────────────────────────────────────
  const patents = [
    { title: "Inhibitors of Phosphoglycerate Dehydrogenase and Uses Thereof", year: 2025, inventors: "Jake Y. Chen et al.", filingInfo: "US patent application filed July 2025 by UAB", relatedResearch: "Pending" },
    { title: "Disease-specific Drug-protein Connectivity Mapping", year: 2010, inventors: "Jake Y. Chen (sole inventor)", filingInfo: "US patent 61/359,429 filed June 2010 by IU", relatedResearch: "Licensed May 2013" },
    { title: "Multi-level Terrains as Visual Analytic Platform for Biomarker Discovery", year: 2010, inventors: "Jake Y. Chen and Shiaofen Fang", filingInfo: "US patent 61/301,509 filed March 2010 by IU", relatedResearch: "Licensed May 2013" },
    { title: "4-protein Biomarker Panel for Lymphoma Diagnosis", year: 2010, inventors: "Jake Y. Chen (sole inventor)", filingInfo: "US patent 61/301,520 filed March 2010 by IU", relatedResearch: "Licensed May 2013" },
    { title: "Mining Protein Interaction Networks", year: 2006, inventors: "Jake Y. Chen (sole inventor)", filingInfo: "US patent 11/526,938 filed 09/2006 by IU", relatedResearch: "Claims abandoned" },
    { title: "Computer Software for Sequence Selection", year: 2005, inventors: "Michael Mittmann, Hui Wang, Jake Y. Chen", filingInfo: "US patent 11/084,309 filed 03/2005 by Affymetrix", relatedResearch: null },
    { title: "Relational Database Operator for Biological Sequence Similarity Search", year: 2001, inventors: "Jake Y. Chen (sole inventor)", filingInfo: "US provisional patent filed Jan 2001", relatedResearch: "Not pursued" },
  ]
  for (const patent of patents) {
    await prisma.patent.create({ data: patent })
  }

  // ─── News Items ──────────────────────────────────────────────────
  const news = [
    { headline: "CONNECT: NIH U54 National AI-Infrastructure Initiative Launched", summary: "Prof. Chen leads CONNECT as Contact MPI, a $9.4M NIH U54-funded initiative building AI-ready biomedical knowledge networks across institutions.", date: new Date("2024-04-01"), pinned: true, published: true },
    { headline: "SPARC Center Established at UAB", summary: "The Systems Pharmacology AI Research Center (SPARC) officially launches under Prof. Chen's direction.", date: new Date("2023-10-01"), pinned: false, published: true },
    { headline: "Bridge2AI Grand Prize Won", summary: "AI.MED team wins the NIH Bridge2AI Program Theme Song Competition Grand Prize.", date: new Date("2024-06-01"), pinned: false, published: true },
    { headline: "Now Recruiting: PhD Students for AI-Driven Drug Discovery", summary: "AI.MED is actively recruiting motivated PhD students for computational drug discovery, knowledge graphs, and AI methods.", date: new Date("2025-01-15"), pinned: true, published: true },
  ]
  for (const item of news) {
    await prisma.newsItem.create({ data: item })
  }

  // ─── Admin User ──────────────────────────────────────────────────
  await prisma.user.create({
    data: {
      email: "admin@aimed-lab.org",
      password: "changeme123", // TODO: hash in production
      name: "Admin",
      role: "ADMIN",
    },
  })

  console.log("Seeding completed successfully!")
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e)
    prisma.$disconnect()
    process.exit(1)
  })
